name: Test Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Install OS dependencies
        run: sudo apt-get install -y bats curl
      - name: Install Python dependencies
        run: sudo pip3 install -r requirements.txt -r requirements-dev.txt
      - name: Run linters
        run: make lint
      - name: Run the tests
        run: make test
